version: '3.0'

services:
  # Fake mail server
  mailserver:
    image: docker.io/haravich/fake-smtp-server
    container_name: af_mail
    restart: unless-stopped
    ports:
      # Mount host port to docker internal port
      - $SMTP_LOCAL_PORT:1025
      - $SMTP_WEB_LOCAL_PORT:1080
  # MySql Server
  mysqldb:
    image: docker.io/mysql:8.1
    container_name: af_db
    restart: unless-stopped
    # load extra environment variables from file
    env_file: ./.env
    # Set manual environment variables
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=AnsibleForms
    ports:
      # Mount host port to docker internal port
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      # Map database location (to maintain persistency)
      - ./data/mysql/db:/var/lib/mysql
      # Map my.cnf file (to maintain persistency)
      - ./data/mysql/my.cnf:/etc/mysql/my.cnf
      # Map init sql scripts
      - ./data/mysql/init:/docker-entrypoint-initdb.d
  # AnsibleForms application
  app:
    # Only start after MySql
    depends_on:
      - mysqldb
    image: docker.io/ansibleguy/ansibleforms:beta
    container_name: af_app
    restart: unless-stopped
    ports:
      # Mount host port to docker internal port
      - $WEBAPP_LOCAL_PORT:$WEBAPP_DOCKER_PORT
    # Load extra environment variables from file
    env_file:
      - ./.env
    # Set environment variables
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - PORT=$WEBAPP_DOCKER_PORT
      - ADMIN_USERNAME=$ADMIN_USERNAME
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - REGEX_FILTER_JOB_OUTPUT=Set naming facts|Merge Extravars|include_tasks|info|debug|set_fact|assert
      # adding python path to add our custom persistent lib location
      - PYTHONPATH=/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/lib/python3.11/site-packages:/app/dist/persistent/python/lib      
    # allow interactive shell
    stdin_open: true
    # allow terminal
    tty: true
    volumes:
      # Mount application folder to host folder (to maintain persistency)
      - ./data:/app/dist/persistent
      # Mount images folder to host folder (to have custom images)
      - ./data/images:/app/dist/views/assets/images    
      # Mount logo (to have custom logo)
      #- ./data/images/mylogo.svg:/app/dist/views/assets/img/logo_ansible_forms_full_white.svg
      # Mount background image (to have custom background)
      #- ./data/bg.jpg:/app/dist/views/assets/img/bg.jpg
      # Map custom functions for js expressions and jq
      - ./data/functions/custom.js:/app/dist/src/functions/custom.js
      - ./data/functions/jq.custom.definitions.js:/app/dist/src/functions/jq.custom.definitions.js
      # Map custom sshkey to local node .ssh location
      - ./data/ssh:$HOME_DIR/.ssh
      - ./data/git/.gitconfig:$HOME_DIR/.gitconfig
      # Map custom ansible.cfg
      - ./data/ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ./data/ansible/roles:/etc/ansible/roles
      - ./data/ansible/collections:/etc/ansible/collections

